---
- name: Get name of Prometheus release
  shell: helm list --all-namespaces | grep prometheus | awk '{print $1}'
  register: release_name
  changed_when: false

- name: Delete Prometheus release
  command: helm delete --namespace default {{ release_name.stdout.strip() }} || true
  ignore_errors: true
  when: release_name.stdout.strip() != ""

- name: Delete prometheus resources, PVC & pv
  shell: |
    kubectl get all -n default -o name | grep prometheus | xargs -n 1 kubectl delete -n default; \
    pvc_name=$(kubectl get pvc -n default -o name | grep prometheus); \
    pv_name=$(kubectl get pvc -n default $pvc_name -o jsonpath='{.spec.volumeName}'); \
    kubectl delete $pvc_name -n default --force; \
    kubectl delete $pv_name -n default --force
  ignore_errors: yes

- name: Delete nfs-omnia release
  command: helm delete nfs-omnia --namespace default
  ignore_errors: true

- name: Delete Spark operator release
  command: helm delete my-release --namespace spark-operator
  ignore_errors: true

- name: Delete spark-operator namespace
  command: kubectl delete namespace spark-operator --force
  ignore_errors: true

- name: Delete mpi-operator resources
  command: kubectl delete all --all --force -n mpi-operator
  register: delete_resources

- name: Delete mpi-operator namespace
  command: kubectl delete namespace mpi-operator --force
  ignore_errors: true